package com.mycompany.agvparking;



/**
 *
 * @author KTS - G2 
 */

import javax.swing.SwingUtilities;


public class ControlUI extends javax.swing.JFrame {

    DataStore ds; 
    private boolean isDemoMode; 
    
    private java.util.List<Integer> unvisitedMissions = new java.util.ArrayList(); 
    
    /**
     * Creates new form ControlUI
     */
    public ControlUI(DataStore ds, boolean isDemoMode) {
        // initComponents();  // The GUI code, generated by NetBeans is not called

        this.ds = ds; 
        this.isDemoMode = isDemoMode; 
        
        initComponents(); 
        setupModeUI(); 
        setTitle("Autopark - " + (isDemoMode ? "Demo-läge" : "Drift-läge")); 
    } 
    
    private void setupModeUI() { 
        if (isDemoMode) { 
            jToggleButton1.setVisible(false); 
            jButton2.setVisible(false); 
            jButton1.setVisible(false); 
            
            appendStatus("Demoläge aktiverat: Beräknar första rutten... \n"); 
            
            unvisitedMissions.clear(); 
            for (int i = 1; i < ds.locations; i++) { 
                unvisitedMissions.add(i); 
            } 
            
            planNextMission(); 
            
            jButton3.setEnabled(true);
            jButton4.setEnabled(true); 
            jButton5.setEnabled(true); 
            
        } else { 
            jToggleButton1.setVisible(false); 
            jButton3.setVisible(false); 
            jButton4.setVisible(false); 
            jButton5.setVisible(false); 
            
            prepareRealModeLog(); 
        } 
    } 
    
    private void prepareRealModeLog() { 
        jScrollPane1.setVisible(false); 
        
        jScrollPane5.setVisible(true); 
        jScrollPane6.setVisible(true); 
        
        txtSent.setText("Utgående kommandon: \n"); 
        txtReceived.setText("Inkommande data: \n"); 
    } 
    
private boolean planNextMission() {
        // Om listan är tom är vi färdiga!
        if (unvisitedMissions.isEmpty()) {
            appendStatus("Alla uppdrag klara! Alla bilar är parkerade.\n");
            return false; 
        }

        OptPlan op = new OptPlan(ds);
        int startX = (int) (ds.LocationX[0] / ds.gridsize);
        int startY = (int) (ds.LocationY[0] / ds.gridsize);
        int startNodeId = (startY * ds.columns) + startX;

        int bestIndex = -1;
        int shortestPathSize = Integer.MAX_VALUE;
        java.util.List<Vertex> bestPath = null;
        int bestDestX = -1;
        int bestDestY = -1;

        appendStatus("Letar efter närmaste lediga parkeringsruta...\n");

        // TESTAR ALLA OBESÖKTA RUTOR FÖR ATT HITTA DEN KORTASTE VÄGEN
        for (int candidateIndex : unvisitedMissions) {
            int destX = (int) (ds.LocationX[candidateIndex] / ds.gridsize);
            int destY = (int) (ds.LocationY[candidateIndex] / ds.gridsize);
            int endNodeId = (destY * ds.columns) + destX;

            op.createPlan(startNodeId, endNodeId);

            if (ds.currentPath != null && !ds.currentPath.isEmpty()) {
                // Är denna väg kortare än vår hittills bästa?
                if (ds.currentPath.size() < shortestPathSize) {
                    shortestPathSize = ds.currentPath.size();
                    bestIndex = candidateIndex;
                    bestPath = new java.util.ArrayList<>(ds.currentPath); // Spara kopia av vägen
                    bestDestX = destX;
                    bestDestY = destY;
                }
            }
        }

        // NÄR VI HAR TESTAT ALLA, KOLLA OM VI HITTADE NÅGON VÄG ALLS 
        if (bestIndex != -1) { 
            appendStatus("Valde parkeringsruta Nr: " + bestIndex + " (Avstånd: " + shortestPathSize + " steg)\n"); 
            
            // Ta bort den valda bilen från "att-göra"-listan 
            unvisitedMissions.remove(Integer.valueOf(bestIndex)); 

            // --- Markera hela p-rutan som hinder --- 
            int carWidthInNodes; 
            int carHeightInNodes; 
            int offsetX; 
            int offsetY; 

            if (bestDestY < (ds.rows / 2)) { 
                carWidthInNodes = 11; 
                carHeightInNodes = 5; 
                offsetX = 1; 
                offsetY = -2; 
            } else { 
                carWidthInNodes = 6; 
                carHeightInNodes = 11; 
                offsetX = -3; 
                offsetY = 1; 
            } 

            for (int dx = 0; dx < carWidthInNodes; dx++) {
                for (int dy = 0; dy < carHeightInNodes; dy++) {
                    int blockX = bestDestX + offsetX + dx;
                    int blockY = bestDestY + offsetY + dy;
                    
                    if (blockX >= 0 && blockX < ds.columns && blockY >= 0 && blockY < ds.rows) {
                        ds.ObstacleMatrix[blockX][blockY] = 1; 
                    }
                }
            }
            // ----------------------------------------

            // Skapa listan för denna specifika Tur och Retur
            java.util.List<Vertex> roundTrip = new java.util.ArrayList<>(bestPath);
            
            // --- NYTT: Fyll på Master-listan istället för att skriva över ---
            int offset = masterDemoPath.size(); // Håller koll på om det är första rutten

            if (masterDemoPath.isEmpty()) {
                masterDemoStops.add(0); // Allra första startpunkten
            }

            // Lägg till vägen DIT
            masterDemoPath.addAll(bestPath);
            masterDemoStops.add(masterDemoPath.size() - 1); // Sparar indexet när vi är framme vid P-rutan

            // Skapa vägen tillbaka (vänd på listan)
            java.util.List<Vertex> returnPath = new java.util.ArrayList<>(bestPath);
            java.util.Collections.reverse(returnPath);
            if (!returnPath.isEmpty()) {
                returnPath.remove(0); // Ta bort första steget så vi inte står stilla vid bytet
            }
            
            // Lägg till vägen HEM
            masterDemoPath.addAll(returnPath);
            masterDemoStops.add(masterDemoPath.size() - 1); // Sparar indexet när vi är tillbaka vid basen

            // VIKTIGT: Vi rör inte ds.demoStep här om vi redan är igång och kör. 
            // Endast om det är den allra första rutten sätter vi den till 0.
            if (offset == 0) {
                ds.demoStep = 0; 
            }
            
            updateRobotPosition();
            return true; // Berättar att vi lyckades ladda en ny rutt

        } else {
            appendStatus("Kunde inte hitta någon väg till resterande bilar. De är förmodligen inbyggda/blockerade!\n");
            unvisitedMissions.clear(); 
            return false; 
        }
    }
            


     


    public void showStatus() {
        System.out.println("Start at: " + ds.LocationX[0] + ", " + ds.LocationY[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new MapPanel(ds);
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtSent = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtReceived = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(578, 550));
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(540, 360));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        jToggleButton1.setText("Demo");
        jToggleButton1.setToolTipText("Tryck för att aktivera demoläget");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton1.setText("Stop");
        jButton1.setToolTipText("AGV avbryter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Start");
        jButton2.setToolTipText("AGV startar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("←");
        jButton3.setToolTipText("tar ett steg bakåt i rutten");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("→");
        jButton4.setToolTipText("Tar ett steg vidare i rutten");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("≫  ");
        jButton5.setToolTipText("Snabbspola");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jScrollPane5.setName("txtSent"); // NOI18N

        txtSent.setColumns(20);
        txtSent.setRows(5);
        jScrollPane5.setViewportView(txtSent);

        jScrollPane6.setName("txtReceived"); // NOI18N

        txtReceived.setColumns(20);
        txtReceived.setRows(5);
        jScrollPane6.setViewportView(txtReceived);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4)
                                        .addGap(12, 12, 12)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Pausa tråden!
        ds.isPaused = true;
        appendStatus("AGVn är pausad...\n");

        // Knappar till popup-ruta
        Object[] options = {"Ja", "Nej"};

        // 2. Visa popup-rutan (JOptionPane)
        int response = javax.swing.JOptionPane.showOptionDialog(
                ControlUI.this,
                "Körningen pausades, fortsätt?",
                "Paus",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0] //Förvald knapp
        );

        // 3. Hantera användarens svar
        if (response == javax.swing.JOptionPane.YES_OPTION) {
            // Användaren klickade "Ja"
            appendStatus("Återupptar körningen...\n");
            ds.isPaused = false; // Släpp pausen!
        } else { // Avsluta samtliga processer om användaren väljer "Nej"           
            System.out.println("Avslutar programmet...");
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    java.util.List<Vertex> masterDemoPath = new java.util.ArrayList<>();
    private java.util.List<Integer> masterDemoStops = new java.util.ArrayList<>(); // Målpunkter för demo
    private javax.swing.Timer forwardTimer; // Timer för framåt-knapp
    private int lastOptimizedLegStart = -1; // Håll koll på vilka instruktioner som senast skickades

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        if (jToggleButton1.isSelected()) {
            jButton2.setEnabled(false); // Inaktivera den riktiga startknappen 
            jToggleButton1.setText("Demo körs..");
            appendStatus("Demoläge aktiverat: Beräknar första rutten...\n");

// Nollställ listan och fyll på med alla mål (1 till ds.locations - 1) 
            unvisitedMissions.clear();
            for (int i = 1; i < ds.locations; i++) {
                unvisitedMissions.add(i);
            }
            planNextMission();

            // Aktivera kontroller 
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);

            repaint();

        } else {
            // Avaktivera demo
            jButton2.setEnabled(true);//Aktivera startknappen
            jToggleButton1.setText("Demo");
            appendStatus("Demoläge avaktiverat\n");

            // Stanna timern om den är igång
            if (forwardTimer != null && forwardTimer.isRunning()) {
                forwardTimer.stop();
            }

            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            ds.currentPath = null;
            repaint();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        appendStatus("AGV får nu köra. Startar... \n");

        if (unvisitedMissions.isEmpty()) {
            unvisitedMissions.clear();
            for (int i = 1; i < ds.locations; i++) {
                unvisitedMissions.add(i);
            }
            triggerNextRealMission();
        }
        ds.isPaused = false; // Släpp spärren 
        ds.isStopped = false;

        jButton2.setEnabled(false);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public String updateRobotPosition() { 
        if (masterDemoPath != null && ds.demoStep >= 0 && ds.demoStep < masterDemoPath.size()) {

            // 1. Hämta data om nuvarande steg
            Vertex v = masterDemoPath.get(ds.demoStep);
            int nodeId = Integer.parseInt(v.getId());
            String baseId = masterDemoPath.get(0).getId();

            // 2. Visa bara rutt för nuvarande delsträcka (Svart väg)
            int segmentStart = 0;
            int searchIndex = ds.demoStep;

            if (v.getId().equals(baseId) && ds.demoStep < masterDemoPath.size() - 1) {
                searchIndex = ds.demoStep + 1;
            }

            for (int i = searchIndex; i >= 0; i--) {
                if (masterDemoPath.get(i).getId().equals(baseId)) {
                    segmentStart = i;
                    break;
                }
            }

            int segmentEnd = masterDemoPath.size() - 1;
            for (int i = searchIndex; i < masterDemoPath.size(); i++) {
                if (masterDemoPath.get(i).getId().equals(baseId) && i > segmentStart) {
                    segmentEnd = i;
                    break;
                }
            }
            ds.currentPath = new java.util.ArrayList<>(masterDemoPath.subList(segmentStart, segmentEnd + 1));

            // 3. Uppdatera robotens position (gula pricken)
            ds.robotX = (nodeId % ds.columns) * ds.gridsize + (ds.gridsize / 2.0);
            ds.robotY = (nodeId / ds.columns) * ds.gridsize + (ds.gridsize / 2.0);

            // 4. HISTORIK-MAGIN: Återställ och rita ut rätt röda bilar!
            ds.clearVisitedAreas(); // Sudda allt tillfälligt

            // Loopa igenom hållplatserna. Varje udda index (1, 3, 5...) är ankomsten till en bil.
            for (int i = 1; i < masterDemoStops.size(); i += 2) {
                int arrivalAtGoalIndex = masterDemoStops.get(i);
                
                // Om vi har "hunnit fram" till denna bil i tidslinjen, måla den röd!
                if (ds.demoStep >= arrivalAtGoalIndex) {
                    Vertex goalVertex = masterDemoPath.get(arrivalAtGoalIndex);
                    int goalNodeId = Integer.parseInt(goalVertex.getId());
                    double goalX = (goalNodeId % ds.columns) * ds.gridsize + (ds.gridsize / 2.0);
                    double goalY = (goalNodeId / ds.columns) * ds.gridsize + (ds.gridsize / 2.0);
                    ds.markAreaAsVisited(goalX, goalY);
                }
            }

            // 5. Output för instruktioner
            int currentLegStart = 0;
            int currentLegEnd = masterDemoPath.size() - 1;

            for (int i = 0; i < masterDemoStops.size() - 1; i++) {
                int startStop = masterDemoStops.get(i);
                int endStop = masterDemoStops.get(i + 1);

                if (ds.demoStep >= startStop && ds.demoStep <= endStop) {
                    if (ds.demoStep == endStop && ds.demoStep != masterDemoPath.size() - 1) {
                        continue;
                    }
                    currentLegStart = startStop;
                    currentLegEnd = endStop;
                    break;
                }
            }

            if (currentLegStart != lastOptimizedLegStart) {
                java.util.List<Vertex> legPath = new java.util.ArrayList<>(masterDemoPath.subList(currentLegStart, currentLegEnd + 1));
                if (ds.instructionQueue != null) ds.instructionQueue.clear(); 
                RouteOptimizer optimizer = new RouteOptimizer(ds);
                System.out.println("\n");
                optimizer.compressPath(legPath); 
                lastOptimizedLegStart = currentLegStart; 
            }

            repaint();
            return "(" + (nodeId % ds.columns) + ", " + (nodeId / ds.columns) + ")"; 
        }
        return "";
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Om roboten körs just nu (av framåt-knappen eller snabbspolning), stoppa den!
        if (forwardTimer != null && forwardTimer.isRunning()) {
            forwardTimer.stop();
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
        }

        if (ds.demoStep <= 0) {
            appendStatus("Demo: Redan vid den absoluta startpunkten.\n");
            return;
        }

        // Hitta FÖREGÅENDE hållplats i historik-listan
        int prevStop = 0;
        for (int i = masterDemoStops.size() - 1; i >= 0; i--) {
            int stop = masterDemoStops.get(i);
            // Vi letar efter den hållplats som är strikt mindre än där vi är nu
            if (stop < ds.demoStep) {
                prevStop = stop;
                break;
            }
        }

        // Hoppa direkt bakåt i tiden till den hållplatsen!
        ds.demoStep = prevStop;
        String pos = updateRobotPosition();
        appendStatus("Demo: Hoppade tillbaka i historiken | Position: " + pos + "\n");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (masterDemoPath == null) {
            return;
        }

        // Om vi är vid slutet av nuvarande resan, ladda nästa bil
        if (ds.demoStep >= masterDemoPath.size() - 1) {
            planNextMission();
            return;
        }

        // Hitta NÄSTA hållplats i vår lista (fram till målet, eller tillbaka till basen)
        int nextStop = masterDemoPath.size() - 1;
        for (int stop : masterDemoStops) {
            if (stop > ds.demoStep) {
                nextStop = stop;
                break;
            }
        }

        final int targetStep = nextStop;
        appendStatus("Demo: Kör sträckan fram till nästa mål/bas...\n");

        // Inaktivera knapparna under körning
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);

        if (forwardTimer != null && forwardTimer.isRunning()) {
            forwardTimer.stop();
        }

        // Starta timer för att köra framåt mjukt
        forwardTimer = new javax.swing.Timer(50, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (ds.demoStep < targetStep) {
                    ds.demoStep++;
                    updateRobotPosition();
                } else {
                    ((javax.swing.Timer) e.getSource()).stop();
                    appendStatus("Demo: Framme!\n");
                    jButton3.setEnabled(true);
                    jButton4.setEnabled(true);
                    jButton5.setEnabled(true);
                }
            }
        });
        forwardTimer.start();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (masterDemoPath == null || ds.demoStep >= masterDemoPath.size() - 1) {
            appendStatus("Inget kvar att snabbspola!\n");
            return;
        }

        appendStatus("Snabbspolar...\n");

        // Inaktivera knappar under körning för att undvika krockar 
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        appendStatus("Snabbspolar från steg " + ds.demoStep + "...\n");

        // Timer börjar loopa direkt från nuvarande ds.demoStep 
        javax.swing.Timer timer = new javax.swing.Timer(30, new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {

                if (ds.demoStep < masterDemoPath.size() - 1) {
                    // Kör ett steg 
                    ds.demoStep++;
                    updateRobotPosition();
                } else {
                    // Rutten är slut (vi är på basen). Dags för nästa! 

                    // planNextMission() testar nu alla bilar och returnerar true om den hittade en 
                    boolean success = planNextMission();

                    if (!success) {
                        // Inga fler bilar i listan, eller alla var inbyggda. Stanna! 
                        ((javax.swing.Timer) e.getSource()).stop();
                        appendStatus("Snabbspolning slutförd.\n");
                        jButton5.setEnabled(true); // Gör så vi kan trycka igen 
                    }
                }
            }
        });

        timer.start();
    }//GEN-LAST:event_jButton5ActionPerformed

    public boolean triggerNextRealMission() {
    boolean success = planNextMission();
    return success;
} 
    
    public void appendStatus(String text) {
    jTextArea1.append(text);
    jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
} 
    
    public void logSent(String text) {
    if (!isDemoMode) {
        txtSent.append("UT: " + text + "\n");
        txtSent.setCaretPosition(txtSent.getDocument().getLength());
    }
} 

    public void logReceived(String text) {
    if (!isDemoMode) {
        txtReceived.append("IN: " + text + "\n");
        txtReceived.setCaretPosition(txtReceived.getDocument().getLength());
    }
} 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextArea txtReceived;
    private javax.swing.JTextArea txtSent;
    // End of variables declaration//GEN-END:variables

}
