package com.mycompany.agvparking;

/**
 *
 * @author KTS - G2 
 */

import javax.swing.SwingUtilities;

public class ControlUI extends javax.swing.JFrame {

    DataStore ds; 
    private boolean isDemoMode; 
    
    private java.util.List<Integer> unvisitedMissions = new java.util.ArrayList(); 
    
    /**
     * Creates new form ControlUI
     */
    public ControlUI(DataStore ds, boolean isDemoMode) {
        // initComponents();  // The GUI code, generated by NetBeans is not called

        this.ds = ds; 
        this.isDemoMode = isDemoMode; 
        
        initComponents(); 
        setupModeUI(); 
        setTitle("Autopark - " + (isDemoMode ? "Demo-läge" : "Drift-läge")); 
    } 
    
    private void setupModeUI() { 
        if (isDemoMode) { 
            jToggleButton1.setVisible(false); 
            jButton2.setVisible(true); 
            jButton1.setVisible(true);
            
            jScrollPane1.setVisible(true);   // Visa stora rutan 
            jScrollPane5.setVisible(false);  // Göm "UT"-rutan 
            jScrollPane6.setVisible(false);  // Göm "IN"-rutan 
            
            appendStatus("Demoläge aktiverat: Beräknar första rutten... \n"); 
            
            unvisitedMissions.clear(); 
            for (int i = 1; i < ds.locations; i++) { 
                unvisitedMissions.add(i); 
            } 
            
            planNextMission(); 
            
            jButton3.setEnabled(true);
            jButton4.setEnabled(true); 
            jButton5.setEnabled(true); 
            
        } else { 
            jToggleButton1.setVisible(false); 
            jButton3.setVisible(false); 
            jButton4.setVisible(false); 
            jButton5.setVisible(false); 
            
            prepareRealModeLog(); 
        } 
    } 
    
    private void prepareRealModeLog() { 
        jScrollPane1.setVisible(false); 
        
        jScrollPane5.setVisible(true); 
        jScrollPane6.setVisible(true); 
        
        txtSent.setText("Utgående kommandon: \n"); // Lägg till körriktning osv. 
        txtReceived.setText("Inkommande data: \n"); // + position, status, hinder, 
    } 
    

    public void showStatus() {
        System.out.println("Start at: " + ds.LocationX[0] + ", " + ds.LocationY[0]);
    }
    
private boolean planNextMission() {
        if (unvisitedMissions.isEmpty()) {
            appendStatus("Alla uppdrag klara! Alla bilar är parkerade.\n");
            return false; 
        }

        OptPlan op = new OptPlan(ds);
        int startX = (int) (ds.LocationX[0] / ds.gridsize);
        int startY = (int) (ds.LocationY[0] / ds.gridsize);
        int startNodeId = (startY * ds.columns) + startX;

        int bestIndex = -1;
        int shortestPathSize = Integer.MAX_VALUE;
        java.util.List<Vertex> outPath = null;

        // 1. HITTA NÄRMASTE MÅLNOD
        for (int candidateIndex : unvisitedMissions) {
            int dX = (int) (ds.LocationX[candidateIndex] / ds.gridsize);
            int dY = (int) (ds.LocationY[candidateIndex] / ds.gridsize);
            
            op.createPlan(startNodeId, (dY * ds.columns) + dX);
            
            if (ds.currentPath != null && ds.currentPath.size() < shortestPathSize) {
                shortestPathSize = ds.currentPath.size();
                bestIndex = candidateIndex;
                outPath = new java.util.ArrayList<>(ds.currentPath);
            }
        }

        if (bestIndex != -1 && outPath != null) { 
            appendStatus("Valde målnod Nr: " + bestIndex + " (Avstånd: " + shortestPathSize + " steg)\n");
            unvisitedMissions.remove(Integer.valueOf(bestIndex)); 
            
//            // Markera målnoden som besökt (Röd färg)
            int destX = (int) (ds.LocationX[bestIndex] / ds.gridsize);
            int destY = (int) (ds.LocationY[bestIndex] / ds.gridsize);
//            ds.ObstacleMatrix[destX][destY] = 2; 

            if (destY < (ds.rows / 2) && destX < ds.columns / 3.3) {
                appendStatus("Utför parkering: Vänster cirkelbåge \n"); 
                // Kalla på parkeringsmanöver (från ny class) ex. 12 - Det som Hanna håller på med 
            } 
            else if (destY < (ds.rows / 2) && destX > ds.columns / 3.3) {
                appendStatus("Utför parkering: Höger cirkelbåge \n"); 
                // Kalla på parkeringsmanöver ex. 12 - Det som Hanna håller på med 
            } 
            else if (destY > (ds.rows / 2) && destX < ds.columns * 0.9) {
                appendStatus("Utför parkering: Vrid vänster och backa \n"); 
                // Kalla på parkeringsmanöver ex. 12 - Det som Hanna håller på med 
            } 
            else if (destY > (ds.rows / 2) && destX > ds.columns * 0.9) {
                appendStatus("Utför parkering: Vertikal parkering vid vägg \n"); 
                // Kalla på parkeringsmanöver ex. 12 - Det som Hanna håller på med 
            } 
            
            // 2. BERÄKNA HEMRESA
            op.createReturnPlan((destY * ds.columns) + destX, startNodeId);
            java.util.List<Vertex> returnPath = new java.util.ArrayList<>(ds.currentPath);
            if (!returnPath.isEmpty()) returnPath.remove(0);

            // 3. GENERERA HÖGUPPLÖST TIDSLINJE (KINEMATIK)
            KinematicsTransformer transformer = new KinematicsTransformer(ds);
            
            int offset = masterDemoPath.size(); 
            if (masterDemoPath.isEmpty()) masterDemoStops.add(0);

            // Förvandla utresan (Lastad = true)
            java.util.List<RobotState> detailedOut = transformer.transformPath(outPath, true);
            
            // --- ÅTERSTÄLL DEN BLÅ LINJEN ---
            if (ds.robotTrajectory != null) {
                ds.robotTrajectory.clear();
                // Plocka ut x/y från vår nya tidslinje och lägg i trajectory-listan
                for (RobotState state : detailedOut) {
                    ds.robotTrajectory.add(new Point2D(state.agvX, state.agvY)); 
                }
            }
            // --------------------------------

            masterDemoPath.addAll(detailedOut);
            masterDemoStops.add(masterDemoPath.size() - 1); 

            // Förvandla hemresan (Lastad = false)
            java.util.List<RobotState> detailedReturn = transformer.transformPath(returnPath, false);
            masterDemoPath.addAll(detailedReturn);
            masterDemoStops.add(masterDemoPath.size() - 1); 

            if (offset == 0) ds.demoStep = 0; 
            
            updateRobotPosition();
            return true; 
        }
        
        appendStatus("Kunde inte hitta någon väg till resterande mål.\n");
        unvisitedMissions.clear(); 
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new MapPanel(ds);
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDemo = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtSent = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtReceived = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(578, 550));
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(540, 360));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        jToggleButton1.setText("Demo");
        jToggleButton1.setToolTipText("Tryck för att aktivera demoläget");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton1.setText("Stop");
        jButton1.setToolTipText("AGV avbryter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextAreaDemo.setEditable(false);
        jTextAreaDemo.setColumns(20);
        jTextAreaDemo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDemo);

        jButton2.setText("Start");
        jButton2.setToolTipText("AGV startar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("←");
        jButton3.setToolTipText("Tar ett steg bakåt i rutten");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("→");
        jButton4.setToolTipText("Tar ett steg vidare i rutten");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("≫  ");
        jButton5.setToolTipText("Snabbspola");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jScrollPane5.setName("txtSent"); // NOI18N

        txtSent.setColumns(20);
        txtSent.setRows(5);
        jScrollPane5.setViewportView(txtSent);

        jScrollPane6.setName("txtReceived"); // NOI18N

        txtReceived.setColumns(20);
        txtReceived.setRows(5);
        jScrollPane6.setViewportView(txtReceived);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(146, 146, 146)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(103, 103, 103)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Pausa tråden!
        ds.isPaused = true;
        appendStatus("AGVn är pausad...\n");

        // Knappar till popup-ruta
        Object[] options = {"Ja", "Nej"};

        // 2. Visa popup-rutan (JOptionPane)
        int response = javax.swing.JOptionPane.showOptionDialog(
                ControlUI.this,
                "Körningen pausades, fortsätt?",
                "Paus",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0] //Förvald knapp
        );

        // 3. Hantera användarens svar
        if (response == javax.swing.JOptionPane.YES_OPTION) {
            // Användaren klickade "Ja"
            appendStatus("Återupptar körningen...\n");
            ds.isPaused = false; // Släpp pausen!
        } else { // Avsluta samtliga processer om användaren väljer "Nej"           
            System.out.println("Avslutar programmet...");
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    java.util.List<RobotState> masterDemoPath = new java.util.ArrayList<>();
    private java.util.List<Integer> masterDemoStops = new java.util.ArrayList<>(); // Målpunkter för demo
    private javax.swing.Timer forwardTimer; // Timer för framåt-knapp
    private int lastOptimizedLegStart = -1; // Håll koll på vilka instruktioner som senast skickades

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        if (jToggleButton1.isSelected()) {
            jButton2.setEnabled(false); // Inaktivera den riktiga startknappen 
            jToggleButton1.setText("Demo körs..");
            appendStatus("Demoläge aktiverat: Beräknar första rutten...\n");

// Nollställ listan och fyll på med alla mål (1 till ds.locations - 1) 
            unvisitedMissions.clear();
            for (int i = 1; i < ds.locations; i++) {
                unvisitedMissions.add(i);
            }
            planNextMission();

            // Aktivera kontroller 
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);

            repaint();

        } else {
            // Avaktivera demo
            jButton2.setEnabled(true);//Aktivera startknappen
            jToggleButton1.setText("Demo");
            appendStatus("Demoläge avaktiverat\n");

            // Stanna timern om den är igång
            if (forwardTimer != null && forwardTimer.isRunning()) {
                forwardTimer.stop();
            }

            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            ds.currentPath = null;
            repaint();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        appendStatus("AGV får nu köra. Startar... \n");
        
        // Starta Bluetooth
        BluetoothTransceiver bt = new BluetoothTransceiver(ds, this); // this är evt
        Thread btThread = new Thread(bt);
        btThread.start();

        if (unvisitedMissions.isEmpty()) {
            unvisitedMissions.clear();
            for (int i = 1; i < ds.locations; i++) {
                unvisitedMissions.add(i);
            }
            triggerNextRealMission();
        }
        ds.isPaused = false; // Släpp spärren 
        ds.isStopped = false;

        jButton2.setEnabled(false);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    
public String updateRobotPosition() { 
    if (masterDemoPath != null && ds.demoStep >= 0 && ds.demoStep < masterDemoPath.size()) {
        // Hämta det förberäknade tillståndet för detta tidssteg
        RobotState state = masterDemoPath.get(ds.demoStep);
        
        // Uppdatera DataStore med exakta koordinater för GUI:t
        ds.robotX = state.agvX;
        ds.robotY = state.agvY;
        ds.axleX = state.axleX; // Bilens bakaxel
        ds.axleY = state.axleY;
        ds.robotAngle = state.angle;
        ds.isLoaded = state.isLoaded;

        // Vid varje nytt uppdrag (leg), kör optimeraren för Bluetooth (Drift-läge)
        // (Samma logik som förut för att trigga RouteOptimizer...)
        
        repaint();
        return String.format("(%.1f, %.1f)", ds.robotX, ds.robotY); 
    }
    return "";
}

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Om roboten körs just nu (av framåt-knappen eller snabbspolning), stoppa den!
        if (forwardTimer != null && forwardTimer.isRunning()) {
            forwardTimer.stop();
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
        }

        if (ds.demoStep <= 0) {
            appendStatus("Demo: Redan vid den absoluta startpunkten.\n");
            return;
        }

        // Hitta FÖREGÅENDE hållplats i historik-listan
        int prevStop = 0;
        for (int i = masterDemoStops.size() - 1; i >= 0; i--) {
            int stop = masterDemoStops.get(i);
            // Vi letar efter den hållplats som är strikt mindre än där vi är nu
            if (stop < ds.demoStep) {
                prevStop = stop;
                break;
            }
        }

        // Hoppa direkt bakåt i tiden till den hållplatsen!
        ds.demoStep = prevStop;
        String pos = updateRobotPosition();
        appendStatus("Demo: Hoppade tillbaka i historiken | Position: " + pos + "\n");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (masterDemoPath == null) {
            return;
        }

        // Om vi är vid slutet av nuvarande resan, ladda nästa bil
        if (ds.demoStep >= masterDemoPath.size() - 1) {
            planNextMission();
            return;
        }

        // Hitta NÄSTA hållplats i vår lista (fram till målet, eller tillbaka till basen)
        int nextStop = masterDemoPath.size() - 1;
        for (int stop : masterDemoStops) {
            if (stop > ds.demoStep) {
                nextStop = stop;
                break;
            }
        }

        final int targetStep = nextStop;
        appendStatus("Demo: Kör sträckan fram till nästa mål/bas...\n");

        // Inaktivera knapparna under körning
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);

        if (forwardTimer != null && forwardTimer.isRunning()) {
            forwardTimer.stop();
        }

        // Starta timer för att köra framåt mjukt
        forwardTimer = new javax.swing.Timer(12, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (ds.demoStep < targetStep) {
                    ds.demoStep++;
                    updateRobotPosition();
                } else {
                    ((javax.swing.Timer) e.getSource()).stop();
                    appendStatus("Demo: Framme!\n");
                    jButton3.setEnabled(true);
                    jButton4.setEnabled(true);
                    jButton5.setEnabled(true);
                }
            }
        });
        forwardTimer.start();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (masterDemoPath == null || ds.demoStep >= masterDemoPath.size() - 1) {
            appendStatus("Inget kvar att snabbspola!\n");
            return;
        }

        appendStatus("Snabbspolar...\n");

        // Inaktivera knappar under körning för att undvika krockar 
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        appendStatus("Snabbspolar från steg " + ds.demoStep + "...\n");

        // Timer börjar loopa direkt från nuvarande ds.demoStep 
        javax.swing.Timer timer = new javax.swing.Timer(7, new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {

                if (ds.demoStep < masterDemoPath.size() - 1) {
                    // Kör ett steg 
                    ds.demoStep++;
                    updateRobotPosition();
                } else {
                    // Rutten är slut (vi är på basen). Dags för nästa! 

                    // planNextMission() testar nu alla bilar och returnerar true om den hittade en 
                    boolean success = planNextMission();

                    if (!success) {
                        // Inga fler bilar i listan, eller alla var inbyggda. Stanna! 
                        ((javax.swing.Timer) e.getSource()).stop();
                        appendStatus("Snabbspolning slutförd.\n");
                        jButton5.setEnabled(true); // Gör så vi kan trycka igen 
                    }
                }
            }
        });

        timer.start();
    }//GEN-LAST:event_jButton5ActionPerformed

    public boolean triggerNextRealMission() {
    boolean success = planNextMission();
    return success;
} 
    
    public void appendStatus(String text) {
    jTextAreaDemo.append(text);
    jTextAreaDemo.setCaretPosition(jTextAreaDemo.getDocument().getLength());
} 
    
    public void logSent(String text) {
    if (!isDemoMode) {
        txtSent.append("UT: " + text + "\n");
        txtSent.setCaretPosition(txtSent.getDocument().getLength());
    }
} 

    public void logReceived(String text) { // Tror inte det här används? 
    if (!isDemoMode) {
        txtReceived.append("IN: " + text + "\n");
        txtReceived.setCaretPosition(txtReceived.getDocument().getLength());
    }
} 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextAreaDemo;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextArea txtReceived;
    private javax.swing.JTextArea txtSent;
    // End of variables declaration//GEN-END:variables

}